### ISSUE TITLE
About GIF

### ISSUE THREAD

**Issue by tonngw** [ABSphreak/ABSphreak#8]
I want to know the "Welcome to ABSphreak's GitHub" GIF, it is how to generate quickly. Is there a website for that?

**Comment by ABSphreak** [comment]
Duplicate of https://github.com/ABSphreak/ABSphreak/issues/4.
Please refer to Issue https://github.com/ABSphreak/ABSphreak/issues/4.

**Comment by tonngw** [comment]
OK, thank you
