### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by iEmaz** [ABSphreak/ABSphreak#9]
Hello, I was curious on how you made that welcome gif at the top of the readme, can you tell me how?

**Comment by Arindam-7** [comment]
You can create on for yourself using [this site](https://msgif.net/)

**Comment by Arindam-7** [comment]
> Hello, I was curious on how you made that welcome gif at the top of the readme, can you tell me how?

You can create one for yourself using [this site](https://msgif.net/).

**Comment by ABSphreak** [comment]
Duplicate of https://github.com/ABSphreak/ABSphreak/issues/4.
Please refer to Issue https://github.com/ABSphreak/ABSphreak/issues/4.
Thanks :)
